### ISSUE TITLE
README unclear on user groups

### ISSUE THREAD

**Issue by amalagaura** [cloudfoundry-community/splunk-firehose-nozzle#108]
What does this mean in the README?

 If `cloud_controller.admin` is not available in the system, switch to use `cloud_controller.admin`.

**Comment by amalagaura** [comment]
#109

**Comment by chenziliang** [comment]
It should be if cloud_controller.admin_read_only  is not available in the system, then switch to use cloud_controller.admin

**Comment by chenziliang** [comment]
Fixing the readme.

**Comment by dtregonning** [comment]
Updated and closing.
Thankyou @amalagaura
