### ISSUE TITLE
Data-gen is enabled even if it is not deployed

### ISSUE THREAD

**Issue by novalytics** [cloudfoundry-community/splunk-firehose-nozzle#116]
Hi, 

Using the splunk-firehose-nozzle for a week now, events are coming in! Very nice!

We noticed that an app name called 'data_gen', which is part of the nozzle. Eventhough we did not deploy the 'data_gen', it is enabled by default?! We used 'make deploy-nozzle' but still, 'data_gen' events are coming in with a rate of ~60k a min! 

We removed the app and deployed it again, but alas. Any ideas?

Kind Regards, 
Jeroen

**Comment by novalytics** [comment]
My fault! We ran a 'deploy' once, instead of a 'deploy-nozzle'. This created a new app 'data_gen', did not notice that! 

Sorry! 

Kind Regards,
Jeroen

**Comment by chenziliang** [comment]
Thanks for raising this problem. `make deploy` will deploy data_gen app which is for testing.
