### ISSUE TITLE
Support for Azure

### ISSUE THREAD

**Issue by sbayyapureddy** [cloudfoundry-community/splunk-firehose-nozzle#117]
Current release doesn't support PCF deployment in Azure. We use PCF in Azure and would like to get support in Azure

**Comment by dtregonning** [comment]
Hi @sbayyapureddy how are you looking to deploy the nozzle in Azure. What Operating System or VM Image types are you looking for?

**Comment by luckyj5** [comment]
Hi @sbayyapureddy, couple more questions:
- What errors are you hitting during nozzle deployment?
- Are you trying to deploy the nozzle using the Tile (Splunk Nozzle for PCF Tile)? or deploying it via CF CLI?
-  Are you using Windows containers/ cell or linux? 
Thanks!

**Comment by sbayyapureddy** [comment]
We are using stem cells Pivotal provides - Ubuntu. I haven't tried it yet. I can try and find out if it works

**Comment by sbayyapureddy** [comment]
We tried Splunk Firehose Nozzle on PCF 1.11 on Azure and it seems to work fine. We had to disable SSL validation for HEC. How can we use SSL for sending data to HEC? Can we add certs on PCF to make that work? Also, is there a way to configure log level debug, info, error, etc.? We don't want to send all firehose data with license limits. Please let us know

**Comment by chenziliang** [comment]
@sbayyapureddy if you deployed nozzle by using Tile, there is a checkbox which is called "Skip SSL validation", you can uncheck that box and do redeployment.

If you are using "cf" command line to do deployment, you can setup the following env variable in your manifest yaml file `SKIP_SSL_VALIDATION_SPLUNK: true`. Here is one reference https://github.com/cloudfoundry-community/splunk-firehose-nozzle/blob/master/ci/nozzle_manifest.yml

**Comment by sbayyapureddy** [comment]
Thank you Chen. We have seen the flag. tried it and we getting errors with Splunk HEC when we unchecked SKIP SSL Validation flag. We don't want to send the logs to SplunkCloud via. Http in production. Getting 503 error.

**Comment by chenziliang** [comment]
Sorry, you will need check that check box to Skip the certification validation. And could you please post the 503 error message here ?

**Comment by chenziliang** [comment]
Close it for now. If there is any issue, please reopen it
