### ISSUE TITLE
Nozzle Stops Posting Events

### ISSUE THREAD

**Issue by ConnorRules** [cloudfoundry-community/splunk-firehose-nozzle#119]
Occasionally the nozzle will stop posting events. We've encountered this a few times at a customer site. During the time the nozzle stops posting there are no changes to PCF that might have caused this. The logs from the nozzle don't say anymore than the following:

`{	[-]	
   ip: 10.3.16.29	
   job: cf-splunk	
   job_index: 42d658c0-38c2-4ce6-8967-dd5692577074	
   log_level: 0	
   logger_source: splunk-nozzle-logger	
   message: splunk-nozzle-logger.No events to post	
   origin: splunk_nozzle	
}`

Here's the notes from our PCF admin on the steps he takes to restart the nozzle and clear this issue up:

- Logged into splunk-nozzle vms and checked logs for errors
- No errors were found in the logs, but the file date was not updated since the outage time period
- Once we decided that splunk nozzles had to be restarted (and approval granted), I ran `bosh restart splunk-nozzle` against each node.
- After running this command, I determined that the nodes didn't actually restart. All the processes still were running their original PID. This was determined by `ps -ef | grep splunk` on the node itself
- Finally I redeployed the splunk deployment with `bosh deploy cf-splunk --recreate`. This recreated all three instances and redeployed the nozzles and forwarders.
- This fully restored the splunk logs and the data flow

**Comment by chenziliang** [comment]
Which version of Splunk nozzle is deployed in prod ? From the log and description above, it seems it is still very old version which is not supported any longer. Could you please try the latest nozzle in master branch to which we made lots of enhancement and bug fixing?

Thank you !

**Comment by luckyj5** [comment]
Hi @ConnorRules, Are you using the latest Splunk-firehose-nozzle release? 
How are you deploying the nozzle? Via Tile? or directly via CLI? 

Your scenario sounds like you are using previous version of splunk-firehose-nozzle which had bosh vms (nozzle and forwarders) in it. 
If you are not using version 1.0.0, I highly recommend you to try the latest version as there are lot of  enhancements. 
If you are using Tile for your deployment, please use the latest from here - https://network.pivotal.io/products/splunk-nozzle/
Thanks!

**Comment by chenziliang** [comment]
closed this issue since it is related to beta version nozzle and there is no feedback for 22 days
