### ISSUE TITLE
[Docs] cloud_controller.admin_read_only not found for cf v241

### ISSUE THREAD

**Issue by miguelcastilho** [cloudfoundry-community/splunk-firehose-nozzle#12]
On the documentation it's written:

> cloud_controller.admin_read_only will work for cf v241 or later. Earlier versions should use cloud_controller.admin instead.

I'm using cf v241 and my UAA doesn't have the `cloud_controller.admin_read_only` group. I had to use the `cloud_controller.admin` group.

Can you double check if the documentation is accurate?

**Comment by chenziliang** [comment]
Doc updated
