### ISSUE TITLE
Ingest volume guidance

### ISSUE THREAD

**Issue by coryminton** [cloudfoundry-community/splunk-firehose-nozzle#122]
Is there a good way to predict how much ingest volume (gb/day) a PCF environment will send to Splunk?

**Comment by chenziliang** [comment]
One nozzle instance can inject around 5MB/s  to Splunk which is around 40GB per day. If CF firehose is large volume, then scale out nozzle to handle the load. It is scale horizontally.

**Comment by chenziliang** [comment]
More sizing information is published in our release notes in PivNet

**Comment by dtregonning** [comment]
@chenziliang i think the question @coryminton is asking is related to determining the size of the Splunk ingest before having to scale out nozzles. If the question is can we predetermine how much data will be sent into Splunk before actually ingesting it. No. It may be a valid feature for discussion though.

**Comment by coryminton** [comment]
Let me clarify...I am looking to understand how much data would be sent to Splunk by a PCF environment, for the purpose of Splunk license impact planning and underlying infrastructure sizing. If you have a customer looking to deploy it and they ask "ok, how much is this going to impact my license utilization" then how do you go about determining that?  

So if a nozzle instance can inject 40GB/day toSplunk indexers, how would you determine the number of nozzles needed based on the PCF environment or the infrastructure it runs on?

I work for Dell EMC and we are working on ways to better integrate Splunk with PCF and our solutions for both.

Thanks and feel free to email me if you'd rather take this there cory.minton@dell.com

**Comment by chenziliang** [comment]
I think something can be done on Cloud Foundry side for the volume prediction.

**Comment by jghiloni** [comment]
The official guidance is you need one instance of your nozzle for every 10,000 messages/second of throughput, just FYI.

**Comment by novalytics** [comment]
From what I understood from some guys from Pivotal, is that 1 PCF environment could potentially deliver 100Gig a day for a full working environment. The customer will have 4 PCF environments, so we scaled x100 + 10% overlap ;-)

Hope this helps!

**Comment by dtregonning** [comment]
Closing after advise was provided. 
@coryminton -> please reach out to me at dtregonning@splunk.com to discuss further if needed.
