### ISSUE TITLE
Firehose Nozzle Tile does not have the APP_CACHE_INVALIDATE_TTL option

### ISSUE THREAD

**Issue by novalytics** [cloudfoundry-community/splunk-firehose-nozzle#124]
Hi! 

Could you help with the following issue: 

Our Customer has an Pivotal Cloud Foundry Solution running with the Splunk Firehose Nozzle version 1.0.0 installed as a Tile. Data is send correctly from the Nozzle into Splunk, but the Nozzle does **not** refresh its fields from time to time. So, if the app guid does not change, but the app name does, the Firehose Nozzle Tile keeps the old app name... 

When using the Tile, the option APP_CACHE_INVALIDATE_TTL seems to be missing. This is present at the GitHub (custom app) version, but not in the Tile. Can this option be added to the tile? This could be the solution about keeping the old app name.

PCF version is 1.1
Splunk Firehose Nozzle is version 1.0.0
Splunk version is 6.6.3

Kind Regards,

Jerome

**Comment by metskem** [comment]
It is actually pcf 1.11, and to add to the above, It looks like the tile does not support adding additional properties like the APP_CACHE_INVALIDATE_TTL, it only allows adding extra values to the EXTRA_FIELDS property (which becomes an envvar for the splunk-nozzle pcf app).
It would be nice if we could have that property (and probably more) configurable on the PCF tile.

(we now manually bosh deploy it, and then add the APP_CACHE_INVALIDATE_TTL envvar to the spunk-nozzle app.

cheers,
Harry

**Comment by chenziliang** [comment]
Hi, 

First thanks for reporting this enhancement. There indeed is a bunch of advanced options which are not exposed to Tile.

May  I ask if deploying the nozzle by using PCF cli is a option to you ?

**Comment by metskem** [comment]
Hi,

not sure what you mean with the "PCF cli", but I think the answer is yes.
What we did as a workaround is completely removing the splunk-nozzle tile, and manually bosh deploy the splunk-nozzle, after deployment we then add the envvar APP_CACHE_INVALIDATE_TTL=30s to the splunk-nozzle CF app, then it works.

cheers,
Harry

**Comment by chenziliang** [comment]
I mean something like "cf push -f ci/nozzle_manifest.yml -u process --random-route". All you config envs can be specified in the manifiest.yml

**Comment by metskem** [comment]
I would be perfectly happy installing the nozzle that way, but I cannot find a binary, and I am not very comfortable doing the go compiles and so on.

**Comment by novalytics** [comment]
Is there a binary which Harry could use to install the nozzle?

**Comment by chenziliang** [comment]
Please go to https://github.com/cloudfoundry-community/splunk-firehose-nozzle/releases/tag/v1.0.0 to grab the binary for Linux AMD64 architecture

**Comment by metskem** [comment]
Ah thanks, now it's there. I will try to manually cf-deploy that one.

cheers,
Harry

**Comment by metskem** [comment]
I successfully managed to install the nozzle as a cf app (without the pcf tile).
As far as I am concerned, we can close the issue...

tx,
Harry

**Comment by novalytics** [comment]
Cool! Thanks for the updates @chenziliang and @metskem!
