### ISSUE TITLE
EXTRA_FIELDS/Additional Fields not searchable in Splunk

### ISSUE THREAD

**Issue by novalytics** [cloudfoundry-community/splunk-firehose-nozzle#125]
Hi!

Our customer is using EXTRA_FIELDS or Additional Fields (Tile) to help the Splunk users with identifing environment from which the events are coming from. The problem is, that the fields are visible in Splunk, but are not actually in the (json) events. Wierd things happen when we try to search with these extra fields.

Could it be possible to add the found EXTRA_FIELDS/Additional Fields to the _json format send out to Splunk? I saw in the nozzle.do that the fields were extracted, so why not add them to the default payload?

This should solve the problem, as it becomes part of the _raw event, which it is not at the moment ;-)

Thanks for the help!

Kind Regards,

Jerome

**Comment by chenziliang** [comment]
May i ask what kind of weird thing  you have. Everything should work, if it is not, there is probably some bug in Splunk Platform.

Why we don't bake the extra fields into raw json ? "fields" act as raw data annotation. It is not raw.

**Comment by novalytics** [comment]
Eg, the customer has 3 firehose nozzles active for their 3 PCF implementations. They have created an extra field "environment" which has the value of the specific environment, the events are coming from.

In Splunk, we see the "environment" field, it is populated with the 3 values. All events has these values, but when searching for these values, no results end up... Eg. Value is dev01ne or prod01us, when searching for the complete value: "environment=dev01ne" no results are found. Looking for: "environment=dev*" ends up with several events, not all! Somehow the extra_field "environment" is handled in a different way than other fields. When we try to rewrite the environment values, which is a default action in Splunk, the origional values are not renamed, but new values are added. These are a few examples... ;-)

When we look at the JSON payload, the environment field is not present, and is somehow send within the metadata. But Splunk cannot use it the way the fields that come within the JSON payload, so if it is possible to add the extra/additional fields to the JSON payload, I think that should solve the issue!

In the code, the events.go and eventwriter.go build up the JSON format for sending/writing the event, there is also code that retrieves the extra_fields values. So I thought, if it is possible to put the extra fields within the other fields (eg. cf_app_name, cf_org_name etc), than the extra fields become part of the JSON payload and are not specially indexed as metadata by Splunk, but the fields are created at search time.

Hope this helps!

**Comment by chenziliang** [comment]
We understand how extra fileds works in Splunk and thanks for the proposal which is fully understood also. Could you please paste a screenshot? User should be able to filter events by using extra fields.

**Comment by novalytics** [comment]
Thanx for the reply Chen, here are some screenshots about the behaviour. 

Search for all events and total events with the "environment" field:
![knipsel1](https://user-images.githubusercontent.com/12949066/35377659-5fb4c06c-01b0-11e8-80dd-52d0a312612b.PNG)

![knipsel2](https://user-images.githubusercontent.com/12949066/35377668-67137312-01b0-11e8-8666-b5d82b49d45e.PNG)

When searching for the complete value of the environment field, the results are 0...
![knipsel3](https://user-images.githubusercontent.com/12949066/35377689-77336ffe-01b0-11e8-8d61-200f6c4dcfe1.PNG)

When searching with a wildcard, there are results, but not all...
![knipsel4](https://user-images.githubusercontent.com/12949066/35377719-91945db8-01b0-11e8-8438-fd798d58ce47.PNG)

Please notice: We have selected the same timerange with every result. 
When searching with every other field found in the JSON, the results are what they should be ;-)

Hope this helps!

Kind Regards, 
Jerome

**Comment by dtregonning** [comment]
Hi Jerome, 
Thanks for providing the extra information. Can you try doing a search using indexed extraction notation and see if the events become searchable?

`index=az_ix_appl environment::d01we`

Don

**Comment by novalytics** [comment]
Hi Don, 

Sure no problem. Here you go!
![knipsel](https://user-images.githubusercontent.com/12949066/35379319-f8d0b35a-01b5-11e8-9ab6-c18d64692fe8.PNG)

**Comment by dtregonning** [comment]
Couple of quick follow ups.
* What version of Splunk are we working with?(6.4 and above will be fine for metadata fields)
* What sourcetype are the events coming through as and does that sourcetype have indexed extractions enabled for it? (You can check through the GUI -> sourcetypes)

There is definitely a nuance here to searching on the meta data fields, ill do some more testing and get back to you.

**Comment by novalytics** [comment]
Hi Don,

The version we are using is Splunk Enterprise 6.6.3. The sourcetypes are coming from the nozzle:
- cf:logmessage
- cf:httpstartstop

The is no special config done for the data coming in. We only have a timestamp transform in place because of the epoch time with nano seconds (%s%9N). So no indexed extractions.

Hope this helps!

Kind Regards,

Jerome

**Comment by chenziliang** [comment]
@novalytics Could you please run the following search with large time range ?

> index=az_ix_appl environment::d01we

**Comment by chenziliang** [comment]
If it doesn't show any result, could you please run this again ?

> index=az_ix_appl environment::*

**Comment by novalytics** [comment]
That works indeed! We discussed this internally, and we could solve this by adding a "fields.conf" to our environment to point to the indexed field. But everytime the customer adds new fields, this could potentially disrupt operation.

**Comment by chenziliang** [comment]
@novalytics wondering why my above searches doesn't solve your problem and need switch to fields.conf ?

**Comment by chenziliang** [comment]
closed it since the indexed fields are searchable
