### ISSUE TITLE
ENABLE_EVENT_TRACING not having any effect

### ISSUE THREAD

**Issue by bdfrost** [cloudfoundry-community/splunk-firehose-nozzle#126]
I am running this as the official PCF tile. I am not getting anything in splunk with sourcetype="cf:splunknozzle" other than startup and shutdown notices. I can see that ENABLE_EVENT_TRACING is set to true in `cf env splunk-firehose-nozzle-1.0.0`:

...
ENABLE_EVENT_TRACING: true
EVENTS: ["HttpStartStop", "LogMessage", "ValueMetric", "CounterEvent", "Error", "ContainerMetric"]
EXTRA_FIELDS: 
...

When using the old tile we would get messages similar to:

{	[-]	
  	 ip:	 10.X.X.X	
  	 job:	 cf-splunk	
  	 job_index:	 cfbdd2d3-5373-412c-ar84-512b7e0f3241	
  	 log_level:	 1	
  	 logger_source:	 splunk-nozzle-logger	
  	 message:	 splunk-nozzle-logger.Posting 25 events	
  	 origin:	 splunk_nozzle	
}

any thoughts on this?

There isnt any output in `cf logs splunk-firehose-nozzle-1.0.0` or with --recent.

**Comment by bdfrost** [comment]
BTW -- this tile is otherwise great and I appreciate all of the effort put into it.

**Comment by bdfrost** [comment]
FYI -- I also spent time looking at the code (eventsink/splunk.go) and found:

if s.config.TraceLogging {
		extraFields["nozzle-event-counter"] = strconv.FormatUint(atomic.AddUint64(&s.eventCount, 1), 10)
		extraFields["subscription-id"] = s.config.SubscriptionID
		extraFields["uuid"] = s.config.UUID
	}

Which looks like it just adds the extra fields but doesn't add the additional messages that speak to the number of messages delivered.

**Comment by chenziliang** [comment]
Having said that, may I ask what’s use case that needs enabling the tracing which is just usually for troubleshooting ?

**Comment by bdfrost** [comment]
What I was looking for was 'Splunk Nozzle Event Counts'. I assumed that meant that it sent along the number of logs that it sent periodically. I think that my assumption might be wrong :)

ENABLE_EVENT_TRACING: Enables event trace logging. Splunk events will now contain a UUID, Splunk Nozzle Event Counts, and a Subscription-ID for Splunk correlation searches.

**Comment by chenziliang** [comment]
@bdfrost it probably relates to https://github.com/cloudfoundry-community/splunk-firehose-nozzle/issues/125, you will need use the search in #125 to do the search if you didn't see the event count etc

**Comment by dtregonning** [comment]
Hi @bdfrost going to close off as it looks like the assumption of functionality may have been of.
Please reopen with comments if anything is needed.
