### ISSUE TITLE
Could not get api /v2/info, unsupported protocol scheme

### ISSUE THREAD

**Issue by bkeelapudi** [cloudfoundry-community/splunk-firehose-nozzle#127]
Error Message:
   2018-02-14T08:01:39.68+0000 [APP/PROC/WEB/0] OUT {"timestamp":"1518595299.681070805","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Failed to run splunk-firehose-nozzle","log_level":2,"data":{"error":"Could not get api /v2/info: Get api.x.y.org/v2/info: unsupported protocol scheme \"\""}}

**Comment by bkeelapudi** [comment]
I did push the app using the manifest.yml configuration.

---

applications:
  - name: splunk-firehose-nozzle
    memory: 64M
    instances: 2
    buildpack: https://github.com/cloudfoundry/go-buildpack#v1.7.14
    health-check-type: none
    no-route: true
    command: splunk-firehose-nozzle
    env:
      GOPACKAGENAME: github.com/cloudfoundry-community/splunk-firehose-nozzle
      SKIP_SSL_VALIDATION: true
      ADD_APP_INFO: true
      API_ENDPOINT: https://x.x.x.org
      API_USER: admin
      API_PASSWORD: xyz
      # Valid values include ValueMetric,CounterEvent,Error,LogMessage,HttpStartStop,ContainerMetric
      EVENTS: LogMessage
      SPLUNK_TOKEN: 
      SPLUNK_HOST: https://xyz.com:8088
      SPLUNK_INDEX: default

**Comment by chenziliang** [comment]
Could you please validate your API endpoint again to make sure it is https or http which matches your Cloud foundry API settings ?
if you are not sure if your cloud foundry API endpoint is using https or not, try http to see if it works.

**Comment by chenziliang** [comment]
BTW, 64mb is a little bit too small. We suggest 512MB

**Comment by bkeelapudi** [comment]
Actually had the wrong API user , fixed this issue.

**Comment by dtregonning** [comment]
Great news, Thanks bkeelapudi we'll close off.
