### ISSUE TITLE
Sourcetype filtering

### ISSUE THREAD

**Issue by zacharya** [cloudfoundry-community/splunk-firehose-nozzle#13]
Story: As a user who is not interested in all of the data on the Firehose, I'd like to be able to filter certain sourcetypes and drop them instead of sending them to the HTTP Event Collector.  I'm open to submitting a PR if you guys are ok with that.

Let me know if it's best practice to filter elsewhere in the Firehose pipeline.

**Comment by shinji62** [comment]
Source = events  no ? So you can use `--events` flag.

**Comment by cholick** [comment]
As @shinji62 mentiond, you can already do this:
https://github.com/cloudfoundry-community/splunk-firehose-nozzle/blob/master/main.go#L47
