### ISSUE TITLE
Scaling Question

### ISSUE THREAD

**Issue by als1860** [cloudfoundry-community/splunk-firehose-nozzle#136]
What metrics and ratio would you recommend to determine the number of instances of the Splunk nozzle to run in a foundation?  

I have looked at the test number in the release note on Pivnet... But I am not seeing any direction on scaling.

via CF Top I am seeing fluctuations between 10,000 - 15,000 messages / second and  and I have 2 instances that fluctuate between ~65% - ~98% CPU each and seem proportional to the number of messages.

I see @jghiloni 's (Hi Josh) statement of ~ 1 nozzle  per 10,000 messages /second.  But this seems some what low as we have/had 15 instances of firehose to syslog in this same foundation and were loosing missing a significant number of messages in splunk.  Is this nozzle really that much more efficient?

**Comment by r2d2c3p0** [comment]
Hi Alan,

We are facing similar issue where we are loosing around 30% logs in Splunk. `cf top` gave us ~35K events/second and we rounded that to 40K and going by Pivotal formula below we currently have 20 Doppler, 5 Traffic Controllers and 4 Nozzle instances deployed.

```
1 Doppler can process 2000 events/second , in my case (40,000 e/s) / (2000 e/s) = 20
Doppler instances = 4 x Traffic Controller
Traffic Controllers instances = Nozzle instances
```

Still, we are still seeing logs getting dropped. Appreciate any input.

**Comment by als1860** [comment]
@r2d2c3p0 The issue when we were seeing lost messages was with Firehose2syslog.  After switching to the Splunk nozzle, as far as I can tell, we seem to not be loosing messages like we were before.  I am currently running 2 nozzle instances in each foundation.

Sorry, that this is not much help.

**Comment by luckyj5** [comment]
Thanks for the update @r2d2c3p0 
So just to clarify, there aren't any issues with `Splunk-Firehose-Nozzle`? 
Also, if you happen to see issues related to nozzle not able to keep up with the generated load, please scale out nozzle and match it with the number of traffic controllers that are running in your deployment.

**Comment by luckyj5** [comment]
Please re-open if needed. 
Closing this issue.
