### ISSUE TITLE
repeated websocket: close 1006 (abnormal closure): unexpected EOF messages

### ISSUE THREAD

**Issue by als1860** [cloudfoundry-community/splunk-firehose-nozzle#137]
I am repeatedly seeing the message,"source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Firehose consumer exits with error","log_level":2,"data":{"error":"websocket: close 1006 (abnormal closure): unexpected EOF"}, in the logs.  I have increased the FIREHOSE_KEEP_ALIVE from 25s to 90s and it does not seem to have any impact on the frequency of this message.

How should I address this and how do I determine if there are messages from the firehose that are not making it to splunk?

**Comment by luckyj5** [comment]
@als1860 Are you still having this issue? The error seems to be related to the firehose as its closing the connection abnormally.  
For data tracing, please set the below configuration setting to true and redeploy the nozzle.
ENABLE_EVENT_TRACING: Enables event trace logging. Splunk events will now contain a UUID, Splunk Nozzle Event Counts, and a Subscription-ID for Splunk correlation searches.

**Comment by luckyj5** [comment]
Hi @als1860, if this issue still exist, please re-open this issue. 
Closing this issue as part of cleanup. Thanks!
