### ISSUE TITLE
How to send splunk nozzle events to splunk

### ISSUE THREAD

**Issue by als1860** [cloudfoundry-community/splunk-firehose-nozzle#138]
How do I get splunk nozzle events/messages forwarded to splunk.

If I add SplunkNozzle to the EVENTS variable, I seem to stop receiving application messages and only receive messages like these (orgin: splunk_nozzle.

5/2/18
3:05:17.542 PM	
{	[-]	
  	 ip:	 10.39.83.59	
  	 log_level:	 1	
  	 logger_source:	 splunk-nozzle-logger	
  	 message:	 splunk-nozzle-logger.Retrieving apps from remote	
  	 origin:	 splunk_nozzle	
}

If I do not add SplunkNozzle to the EVENTS variable, I do not receive any messages with 'origin: splunk_nozzle'	but do seem to receive app messages.

**Comment by luckyj5** [comment]
Splunk nozzle streams its logs to Splunk by default and could be searched by using search = `sourcetype=cf:splunknozzle`

**Comment by luckyj5** [comment]
Hi @als1860, Please re-open this issue if needed. 
Closing this issue as part of the cleanup. Thanks!
