### ISSUE TITLE
Missing logs of source_type SSH

### ISSUE THREAD

**Issue by n-gottam** [cloudfoundry-community/splunk-firehose-nozzle#139]
Noticed that SSH logs are missing (when user accesses an application container through SSH) Sample log will look like this - 
{"cf_app_id":"de5abfe7-c270-4f37-924b-97df10d8705d","cf_app_name":"app-usage-server","cf_ignored_app":false,"cf_org_id":"f519b0d7-a7b4-4b13-8ec9-1046b8c5bd0a","cf_org_name":"system","cf_origin":"firehose","cf_space_id":"ff20b022-38c1-4c25-b58a-5c7c6f89c927","cf_space_name":"system","deployment":"cf","event_type":"LogMessage","ip":"3.3.22.34","job":"diego_brain","job_index":"e178d5a6-1d2c-43b3-a5de-1925e641e208","message_type":"OUT","msg":"Successful remote access by 3.3.74.104:43274","origin":"ssh-proxy","source_instance":"0","**source_type":"SSH"**,"timestamp":1525361571564350214}
cf_app_id =	de5abfe7-c270-4f37-924b-97df10d8705d cf_app_name =	app-usage-server cf_ignored_app =	false cf_org_id =	f519b0d7-a7b4-4b13-8ec9-1046b8c5bd0a cf_org_name =	system cf_space_id =	ff20b022-38c1-4c25-b58a-5c7c6f89c927 cf_space_name =	system host =	3.3.22.34 job =	diego_brain source =	diego_brain sourcetype =	cf:logmessage

This is being sent by the splunk nozzle tile but not the app.

Is this expected? Any thoughts?

Thank you!

**Comment by luckyj5** [comment]
@n-gottam Just to clarify, these logs are being sent to Splunk when deployed using the Splunk nozzle tile? 
Which app are you referring to?

**Comment by luckyj5** [comment]
@n-gottam Please re-open if this issue still exist. 
Closing this issue as part of cleanup. Thanks!
