### ISSUE TITLE
Make github-release splunk-firehose-nozzle.Linux.AMD64 binary executable

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry-community/splunk-firehose-nozzle#140]
I would like to consume the v1.0.0 github release in my automation pipeline and use the `splunk-firehose-nozzle.Linux.AMD64` binary as an executable to be run on Cloud Foundry.

However, when you push the `splunk-firehose-nozzle.Linux.AMD64` binary as an app to be executed, you get executable permissions errors. If you take that binary and run `chmod +x splunk-firehose-nozzle.Linux.AMD64` on it, and *then* push it, Cloud Foundry can execute it.

It would be more convenient for consumers if the `splunk-firehose-nozzle.Linux.AMD64` binary were uploaded with the `chmod +x` permissions were made and commited into `git`.

Do you think you could either re-upload the binary with executable permissions added to it?

Thanks!

**Comment by luckyj5** [comment]
Thanks for raising this issue @aegershman. 
We will make the necessary updates and re-upload the binary with correct set of permissions during the next maintenance window.

**Comment by luckyj5** [comment]
@aegershman Pardon the delay, it will be updated in the next maintenance window which currently is in scheduling process. Will let you know when it's updated. Thanks!

**Comment by luckyj5** [comment]
Hi @aegershman, release v1.0.2 is available on github and has necessary permissions (chmod +x) 
Please re-open/ create a new issue if any problems. Thanks!

**Comment by aegershman** [comment]
@luckyj5 By the way I'm so sorry, I'm a dummy. It turns out that even if you do set chmod +x executable permissions on a binary, when they're uploaded to github releases, the executable permissions are stripped away. The only way to preserve them is if they're bundled up into something like a tarball & have the tarball be a part of the release.

So it turns out that consuming the github-release directly isn't possible without chmod'ing it first regardless.

I should've checked that first. Sorry about that.
