### ISSUE TITLE
support for PAS 2.2

### ISSUE THREAD

**Issue by patrick-huber-pivotal** [cloudfoundry-community/splunk-firehose-nozzle#141]
On Pivnet only 2.1 support is listed. A customer wants to upgrade to 2.2 to mitigate an issue with smoke tests failing in the autoscaler and can't do the migration until all of the tiles are upgraded. Is there a timeline on support for 2.2?

**Comment by als1860** [comment]
Has anyone been able to test ion PAS 2.2 yet?  if so, what were the results?

**Comment by luckyj5** [comment]
Release has been updated to support PAS 2.2 and 2.3. 
New release (coming on soon) will include support for PAS 2.4
Thanks!

**Comment by luckyj5** [comment]
Release v1.0.2 includes support for PAS 2.4 
Thanks!
