### ISSUE TITLE
Logs are getting dropped in Splunk

### ISSUE THREAD

**Issue by r2d2c3p0** [cloudfoundry-community/splunk-firehose-nozzle#142]
#We are facing an issue where we are loosing around 30% logs in Splunk. `cf top` gave us ~35K events/second and we rounded that to 40K and going by Pivotal formula below we currently have 20 Doppler, 5 Traffic Controllers and 4 Nozzle instances deployed.

```
1 Doppler can process 2000 events/second , in my case (40,000 e/s) / (2000 e/s) = 20
Doppler instances = 4 x Traffic Controller
Traffic Controllers instances = Nozzle instances
```

Still, we are seeing logs getting dropped. Appreciate any input.

**Comment by luckyj5** [comment]
Can you please help with the below info to investigate further: 
- How are you deploying the Nozzle? (Via the Tile or via CLI?) 
- Are you noticing any errors/ warnings in the Splunk Firehose Nozzle logs? If so, can you please share the logs? 
Also, If you want to scale a nozzle, the number of nozzle instances should match the number of Traffic Controller instances as recommended here https://docs.pivotal.io/pivotalcf/2-2/loggregator/log-ops-guide.html#scaling-nozzles 

Thanks!

**Comment by luckyj5** [comment]
Please re-open if needed. 
Closing this issue.
