### ISSUE TITLE
Update Tile to point to develop branch

### ISSUE THREAD

**Issue by luckyj5** [cloudfoundry-community/splunk-firehose-nozzle#145]
Tile version 1.0.1 is tagged with Splunk-Firehose-Nozzle feature branch. Need to update the Tile to tag it with develop branch

**Comment by aegershman** [comment]
(apologies for being obnoxious about this, but when you cut a release for `1.0.1` on this github repo, please consider making the binary executable [#140])

**Comment by luckyj5** [comment]
Fixed.
