### ISSUE TITLE
Change value of host-field for cf:splunknozzle

### ISSUE THREAD

**Issue by hanswurscht** [cloudfoundry-community/splunk-firehose-nozzle#15]
Using latest revision from 09.03.2017 events for sourcetype `cf:splunknozzle` are created with the field `host=localhost`.

It would be better, if a more recognizable value (fqdn, hostname or ip-address) for the field host was used.

Thanks!

**Comment by chenziliang** [comment]
Fixed in https://github.com/cloudfoundry-community/splunk-firehose-nozzle/pull/35
