### ISSUE TITLE
PAS 2.4 Support

### ISSUE THREAD

**Issue by bmullan-pivotal** [cloudfoundry-community/splunk-firehose-nozzle#152]
Current PivNet docs show support for PAS 2.3.*, 2.2.*, 2.1.*, 2.0.*, 1.12.* or 1.11.*.

Will it work with PAS 2.4 which has just been released ?

**Comment by luckyj5** [comment]
@bmullan-pivotal We are working on adding support for PAS 2.4 and it's scheduled to release on March 1st 2019.

**Comment by luckyj5** [comment]
v1.0.2 includes support for PAS 2.4
Thanks!
