### ISSUE TITLE
[Docs] Rearrange README sections

### ISSUE THREAD

**Issue by rarsan** [cloudfoundry-community/splunk-firehose-nozzle#16]
- Move how-to use sections (including push app to cf) before how-to contribute.
- Add more details to how-to use section around API_USER/API_PASSWORD and uaac commands

**Comment by Dontre-Splunk** [comment]
Also need to update the README to add 'HEC-RETRIES - Number of retries before dropping events' to the list of env variables.

**Comment by Dontre-Splunk** [comment]
Fixed in Pull #75
