### ISSUE TITLE
Add ability to forward http events to /raw HEC endpoint

### ISSUE THREAD

**Issue by Ekotlikoff** [cloudfoundry-community/splunk-firehose-nozzle#165]
It would be nice to support the ability to forward http events to the raw HEC endpoint, allowing for more configurable parsing of the events.

Currently events are forwarded only to "/services/collector" (line 75 of eventwriter/splunk.go) and there is not an option to forward to "/services/collector/raw".  I am considering adding a configurable variable named SplunkHecEndpoint that defaults to "/services/collector".  This would allow folks to set it to "/services/collector/raw" or if indexer acknowledgment is desired: "/services/collector/raw?channel=xxxx" (as per http://dev.splunk.com/view/event-collector/SP-CAAAE8Y#raw).

**Comment by luckyj5** [comment]
@Ekotlikoff Pardon the delay and thanks for creating this issue and raising a PR for it, really appreciate it. 
Wanted to update you that we raised an ER to add timestamp extraction support for /event endpoint (similar to /raw endpoint) for Splunk HEC and feature will be available in future releases of Splunk. (not scheduled yet). 
Hence we won't need HEC /raw endpoint support in Splunk Firehose Nozzle. 
Please let me know if any questions and re-open this issue if necessary. Thanks!
