### ISSUE TITLE
type *http.Server has no field or method Shutdown

### ISSUE THREAD

**Issue by Ekotlikoff** [cloudfoundry-community/splunk-firehose-nozzle#166]
I'm getting the below error when running make test on a fresh clone:

testing/cloud_controller_mock.go:63: c.server.Shutdown undefined (type *http.Server has no field or method Shutdown)

go version: go version go1.7.6 darwin/amd64
glide -v: glide version v0.12.3

Are there any additional steps I should follow for setup?

**Comment by luckyj5** [comment]
@Ekotlikoff I have not seen this error before but I would check if all my go dependencies are upto date. Can you please try upgrading `go` version in your env to 1.8 or 1.9 and also run `go get -t ./...` before you try `make test` again? 
Let me know if any issues. Thanks!

**Comment by Ekotlikoff** [comment]
Upgrading go to 1.8 fixed it, thank you!
