### ISSUE TITLE
Add similar functionality of BoltDB cache from firehose-to-syslog nozzle

### ISSUE THREAD

**Issue by drutstein** [cloudfoundry-community/splunk-firehose-nozzle#17]
The [Firehose-to-Syslog Nozzle](https://github.com/cloudfoundry-community/firehose-to-syslog) provides additional ability to map Apps to Spaces and Orgs which is invaluable for mapping activity to a higher abstraction.  

Because this doesn't exist in Splunk Firehose Nozzle the visibility of Org/Space activity is limited unless we map it to a lookup and pull the data from CCDB, but unfortunately this is only a point-in-time pull and may miss some app instances that would have been created after the CCDB pull.

**Comment by rarsan** [comment]
@drutstein , Splunk Firehose Nozzle already enriches application events by mapping corresponding app, space & org name using a managed cached lookup. Make sure to set `ADD_APP_INFO=true` in your app manifest.
I'll close this, but please re-open if anything more is needed here.
