### ISSUE TITLE
"[BUG]"x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by Muruganfly03** [cloudfoundry-community/splunk-firehose-nozzle#188]
**What happened**
splunk-firehose-nozzle-1.0.2 VM post the below error.
{"timestamp":"1560782077.537144899","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Unable to talk to Splunk","log_level":2,"data":{"error":"Post https://*****.com:8088/services/collector: x509: certificate has expired or is not yet valid"}}

**What you expected to happen**:
All logs should forward fromPCF to Splunk. Right now firehose-to-syslog performing logs to Splunk.

*Environment**:
- Cloud Foundry version - 2.3.5
- Splunk version: 1.0.2

**Comment by luckyj5** [comment]
@Muruganfly03 Looks like a problem with Splunk certificate which either is invalid or expired. 
Can you please try this link which talks about how to check expired certs and how to renew them? https://answers.splunk.com/answers/596538/renewing-serverpem-certificate.html#answer-597460

**Comment by luckyj5** [comment]
@Muruganfly03 Were you able check certs and renew them? Thanks!

**Comment by luckyj5** [comment]
@Muruganfly03 are you still noticing cert issue?

**Comment by luckyj5** [comment]
Closing this issue due to no update. Please re-open or create new issue if needed. Thanks!
