### ISSUE TITLE
"[BUG]" Refresh Token has expired after 14 days

### ISSUE THREAD

**Issue by nrekretep** [cloudfoundry-community/splunk-firehose-nozzle#200]
**What happened**
Our splunk firehose nozzle instances stopped working because they could not communicate with the cloud controller api anymore. 

The error message in the logs states that the refresh token has expired. 

Currently the splunk firehose nozzle authenticates itself with the configured username/password credentials and gets an access token and a refresh token. When the access token expires it will be renewed using the refresh token and the default client_id/client_secret credentials. 
Unfortunately the refresh token itself will not be renewed and expires after 14 days in our installation. 

**What you expected to happen**:
I would expect that the splunk firehose nozzle just works in the background like the other Cloud Foundry components and uses therefore the same authentication mechanisms. 
Restarting the splunk firehose nozzle every 14 days is not really practical in a production environment. 

**How to reproduce it (as minimally and precisely as possible)**:
Start the splunk firehose nozzle and wait until the refresh token has expired. 

**Anything else we need to know?**:
Are there any plans to use a client credentials flow instead of the password flow for the splunk firehose nozzle?

**Environment**:
- Cloud Foundry version: Cloud Controller API Version 2.131
- Go version: go buildpack v1.8.39
- Splunk version: Splunk Firehose Nozzle for PCF v1.1.0
- Others:

**Comment by nrekretep** [comment]
Hi,
is there any chance that this gets fixed until the next release?
We are currently automating the restarts of the firehose nozzle...

Any feedback on this is greatly appreciated. 

Thanks!

**Comment by luckyj5** [comment]
@nrekretep Pardon the delay, we are currently looking into this issue and the fix will be included in the next release which is not scheduled yet. Will keep you posted. Thanks!

**Comment by simmyxavier** [comment]
We face the same issue after upgrading Splunk PCF tile from v1.0.x to v1.1.x

**Comment by luckyj5** [comment]
Fixed in v1.1.2 release.
