### ISSUE TITLE
"[BUG]" - nozzle fails to build on cf push

### ISSUE THREAD

**Issue by anishp55** [cloudfoundry-community/splunk-firehose-nozzle#210]
**What happened**
cannot cf push this nozzle to a cf foundations

**What you expected to happen**:
cf push will push the nozzle to the platform and build it
**How to reproduce it (as minimally and precisely as possible)**:
git clone to a system, checkout the v.1.1.2 tag and cf push
**Anything else we need to know?**:
Staging app and tracing logs...
   Downloading go_buildpack...
   Downloaded go_buildpack
   Cell 27b22551-304f-4cfe-978f-c3b0638358cf creating container for instance 5ac171a4-3019-436b-a615-2259abd009f2
   Cell 27b22551-304f-4cfe-978f-c3b0638358cf successfully created container for instance 5ac171a4-3019-436b-a615-2259abd009f2
   Downloading app package...
   Downloaded app package (7.3M)
   -----> Go Buildpack version 1.8.41
          **WARNING** [DEPRECATION WARNING]:
          **WARNING** Please use AppDynamics extension buildpack for Golang Application instrumentation
          **WARNING** for more details: https://docs.pivotal.io/partners/appdynamics/multibuildpack.html
   -----> Installing godep 80
          Download [https://buildpacks.cloudfoundry.org/dependencies/godep/godep-v80-linux-x64-cflinuxfs3-b60ac947.tgz]
   -----> Installing glide 0.13.2
          Download [https://buildpacks.cloudfoundry.org/dependencies/glide/glide-v0.13.2-linux-x64-cflinuxfs3-b50997e2.tgz]
   -----> Installing dep 0.5.3
          Download [https://buildpacks.cloudfoundry.org/dependencies/dep/dep-v0.5.3-linux-x64-cflinuxfs3-b9679cb1.tgz]
   -----> Installing go 1.12.6
          Download [https://buildpacks.cloudfoundry.org/dependencies/go/go1.12.6.linux-amd64-cflinuxfs3-888b9bf8.tar.gz]
          Note: skipping (glide install) due to non-empty vendor directory.
          **WARNING** Installing package '.' (default)
   -----> Running: go install -tags cloudfoundry -buildmode pie .
   events/events.go:9:2: cannot find package "github.com/sirupsen/logrus" in any of:
   	/tmp/gobuildpack.gopath501579198/.go/src/github.com/cloudfoundry-community/splunk-firehose-nozzle/vendor/github.com/sirupsen/logrus (vendor tree)
   	/tmp/contents958607622/deps/0/go1.12.6/go/src/github.com/sirupsen/logrus (from $GOROOT)
   	/tmp/gobuildpack.gopath501579198/.go/src/github.com/sirupsen/logrus (from $GOPATH)
          **ERROR** Unable to compile application: exit status 1
   Failed to compile droplet: Failed to run finalize script: exit status 12
   Exit status 223
   Cell 27b22551-304f-4cfe-978f-c3b0638358cf stopping instance 5ac171a4-3019-436b-a615-2259abd009f2
   Cell 27b22551-304f-4cfe-978f-c3b0638358cf destroying container for instance 5ac171a4-3019-436b-a615-2259abd009f2
   Cell 27b22551-304f-4cfe-978f-c3b0638358cf successfully destroyed container for instance 5ac171a4-3019-436b-a615-2259abd009f2
Error staging application: App staging failed in the buildpack compile phase
FAILED

**Environment**:
- Cloud Foundry version
 cf-deployment 9.5.0
- Go version
go-buildpack-cflinuxfs3-v1.8.41.zip
- Splunk version:
n/a
- Others:

**Comment by anishp55** [comment]
so i managed to get around this by doing the following
setup a new clean instance and install glide and the go tools.
clone the src into src1/github.com/cloudfoundry-community/splunk-firehose-nozzle
enter the directory and run glide install
then follow the deploy directions.

**Comment by luckyj5** [comment]
Thanks for the update @anishp55. 
You can also run `make` before `cf push` which install all deps. `cf push' skips glide install due to non empty vendor directory.

**Comment by luckyj5** [comment]
Closing since its resolved. Please re-open/ create new if anything.

**Comment by michaelmccaskill** [comment]
So I work with Anish and was able to replicate this. I fixed by renaming:
```
$ mv vendor/github.com/Sirupsen vendor/github.com/sirupsen
```
and the `cf push` worked.
