### ISSUE TITLE
"[BUG]"

### ISSUE THREAD

**Issue by ticteam** [cloudfoundry-community/splunk-firehose-nozzle#215]
**What happened**
while i try to "make deploy-nozzle", I got the following error:

**What you expected to happen**:
successful > "make deploy-nozzle" 

**How to reproduce it (as minimally and precisely as possible)**:
make deploy-nozzle

**Anything else we need to know?**:

**Environment**:
- Cloud Foundry version > cf Version 6.48.0+ca3deaa94.2019-12-04
- Go version  >  1.13.5
- Splunk version: *
- Others: centos 7

while i try to "make deploy-nozzle", I got the following error:
-----> Running: go install -tags cloudfoundry -buildmode pie .
   events/events.go:9:2: cannot find package "github.com/sirupsen/logrus" in any of:
        /tmp/gobuildpack.gopath397160155/.go/src/github.com/cloudfoundry-community/splunk-firehose-nozzle/vendor/github.com/sirupsen/logrus (vendor tree)
        /tmp/contents214595125/deps/0/go1.13.5/go/src/github.com/sirupsen/logrus (from $GOROOT)
        /tmp/gobuildpack.gopath397160155/.go/src/github.com/sirupsen/logrus (from $GOPATH)
          **ERROR** Unable to compile application: exit status 1
   Failed to compile droplet: Failed to run finalize script: exit status 12
   Exit status 223

I think the reason is that uppercase in path "splunk-firehose-nozzle/vendor/github.com/Sirupsen/logrus/" 

wrong: Sirupsen --> correct sirupsen 

after changing it local, the "make *" was successful 

greetings

**Comment by luckyj5** [comment]
@ticteam, Thanks for reporting this issue. Which branch were you using when trying make-deploy? 
sirupsen is in lower case in master branch here - https://github.com/cloudfoundry-community/splunk-firehose-nozzle/blob/master/glide.lock#L64.

**Comment by ticteam** [comment]
hi, 
you are right, but please have a look into the folder: https://github.com/cloudfoundry-community/splunk-firehose-nozzle/tree/master/vendor/github.com/Sirupsen 
uppercase ;)

**Comment by luckyj5** [comment]
@ticteam Thanks for the update :) 
We'll update this to lowercase in the next release of the Splunk nozzle.  
Thank you!

**Comment by luckyj5** [comment]
Change is merged to develop (https://github.com/cloudfoundry-community/splunk-firehose-nozzle/pull/217) 
Will be included in the upcoming release.
