### ISSUE TITLE
[ENHANCEMENT] include container hostname in logs

### ISSUE THREAD

**Issue by xyloman** [cloudfoundry-community/splunk-firehose-nozzle#243]
**What would you like to be added**
Include container hostname in logs.

**Why is this needed**:
In order to correlate logs with application performance monitoring tools like newrelic.

**Comment by luckyj5** [comment]
@xyloman Thanks for reaching out. Can you please provide an example? 
Also, which container you referring to?

**Comment by xyloman** [comment]
Each application instance has a unique hostname which can be found when ssh'ing into an instance of the application and running the hostname command it is returned. Some have asked if it would be possible to include this information along with the app name index etc metadata.

**Comment by luckyj5** [comment]
Thanks for the update. 
If hostname is a part of event envelope which Splunk nozzle receives, we can look into it to add it. But if hostname is not exposed through event payload or Cloud controller endpoint, it wouldn't be possible to attach hostname with the logs. 
I'll look into it and provide you with an update. 
Thank you!

**Comment by luckyj5** [comment]
Hi @xyloman, hope you doing well. I looked into hostname field and found out that hostname value is same as `instance guid`, can you please confirm the same from your side? 
If yes, `instance guid` data could be exposed using `tags` data, which will be addressed in the future release of the nozzle. 
Please let me know if any questions. Thanks!

**Comment by xyloman** [comment]
@luckyj5 this sounds fantastic.  Thank you for following up.

**Comment by luckyj5** [comment]
`tags` are now included with the events when configured in the nozzle. Available with latest release v1.2.3. Thanks!
