### ISSUE TITLE
Potential consecutive calls in quick succession to LoggingSplunk.indexEvents()

### ISSUE THREAD

**Issue by Dontre-Splunk** [cloudfoundry-community/splunk-firehose-nozzle#25]
Inside github.com/cloudfoundry-community/splunk-firehose-nozzle/drain/logging_splunk.googging_splunk.go

Call to LoggingSplunk.indexEvents() can happen in 2 scenarios:
1) ticker reaches flush window
2) Batch Number reached.

In a scenario where say the flush window is 10 secs and the batch number limit is reached at 9.5secs
a call to indexEvents will happen twice in half a second.

**Comment by Dontre-Splunk** [comment]
tested subsequent indexes.
Below shows consistent use of both batch number trigger and flush window trigger

![screen shot 2017-06-09 at 2 13 53 pm](https://user-images.githubusercontent.com/17054614/26994792-17d8b8c6-4d1e-11e7-9a92-49fc60f28667.png)
<img width="636" alt="screen shot 2017-06-09 at 2 13 49 pm" src="https://user-images.githubusercontent.com/17054614/26994793-17f2277a-4d1e-11e7-8604-3af1098c7c1d.png">

**Comment by chenziliang** [comment]
Closed in https://github.com/cloudfoundry-community/splunk-firehose-nozzle/pull/29
