### ISSUE TITLE
Need to push Splunk Firehose Nozzle apps with Rolling App Deployments manner in Post-Deploy Errands

### ISSUE THREAD

**Issue by AkihiroKitada** [cloudfoundry-community/splunk-firehose-nozzle#272]
**What would you like to be added**
Need to push Splunk Firehose Nozzle apps with Rolling App Deployments manner with "cf push --strategy rolling" in Post-Deploy Errands.

**Why is this needed**:
Currently, if deploying Splunk Firehose Nozzle app instances in Post-Deploy Errands of Apply Changes, those application instances are pushed with using simple "cf push" command. This causes temporary down time with Splunk Firehose Nozzle app and cf related logs are not drained to Splunk while recreating application instances in Post-Deploy Errands.

Those cf logs should be drained to Splunk even if deploying Splunk Firehose Nozzle app instances in Post-Deploy Errands of Apply Changes.

To prevent the temporary down time causing log lost situation in Splunk, I wonder whether "cf push --strategy rolling" works to redeploy Splunk Firehose Nozzle app instances in Post-Deploy Errands of Apply Changes.

**Additional context**
N/A.

**Comment by luckyj5** [comment]
Splunk Tile is built using tile-generator and is dependent on tile-generator and will probably require a code change here - https://github.com/cf-platform-eng/tile-generator/blob/8c41a5790ed81bf6c0baa6d97077e485bdd40ff3/tile_generator/templates/jobs/deploy-all.sh.erb 

Have added this to the backlog and will revisit once tile-generator is updated.
