### ISSUE TITLE
Release 1.2.3 Breaks on Oauth Token Retrieval from cfapi

### ISSUE THREAD

**Issue by gaigaslab-operations** [cloudfoundry-community/splunk-firehose-nozzle#302]
We upgraded to Tile 1.2.3 from 1.2.2
Immediately, the splunk-nozzle-1.2.3 app started crashing after reporting that it could not get a token from the api endpoint - authorization error.

I don't have the logs right now, since we reverted to 1.2.2 to recover.  I will reproduce on our sandbox foundation and provide the logs.

**Comment by luckyj5** [comment]
Fixed and available with 1.2.4 release
