### ISSUE TITLE
Can the nozzle be used to send data to another HEC other than Splunk?

### ISSUE THREAD

**Issue by lcpldrm** [cloudfoundry-community/splunk-firehose-nozzle#317]
I am trying to configure this to send data to another HEC outside of Splunk, as far as I can tell all of the data arrives without issue but it appears I get an error back from the nozzle for each event that is passed.

"log_level":2,"data":{"Retry attempt":1,"error":"Post \[https://.com:8088/services/collector]\: EOF"

Is it possible to leverage this app to send to a non Splunk HEC destination, or is this hard coded to expect a Splunk HEC endpoint?

Thank you
Regards,

**Comment by kashyap-splunk** [comment]
This nozzle is intended for Splunk only, and tested with Splunk only. Non-Splunk destination is not supported using this nozzle.

**Comment by lcpldrm** [comment]
Awesome thank you so much for the assistance.
Regards,

**Comment by kashyap-splunk** [comment]
Closing the issue, feel free to reopen/open-new if have more queries.
