### ISSUE TITLE
"[BUG]" The nozzle dropping events.

### ISSUE THREAD

**Issue by chethanktmdell** [cloudfoundry-community/splunk-firehose-nozzle#330]
**What happened**
The nozzle dropping events.

**What you expected to happen**:
The events are being dropped while reading from the PCF and forwarding to Splunk
**How to reproduce it (as minimally and precisely as possible)**:
NA

**Anything else we need to know?**:
NA

**Environment**:
- Cloud Foundry version VMware : TAS for VMs v2.13.7
- Go version : go v1.9.49
- Splunk version: 8.2.7
- Others:

**Comment by harshit-splunk** [comment]
Hi @chethanktmdell, it is expected from the nozzle to drop data in the following scenarios:

- nozzle is the bottleneck(Incoming data rate is more than the nozzle can handle)
- Splunk is the bottleneck (It is taking more time/retries to push events to splunk)

Can you check what is the bottleneck in your environment?
