### ISSUE TITLE
[Question] New Nozzle Release

### ISSUE THREAD

**Issue by tstcw** [cloudfoundry-community/splunk-firehose-nozzle#342]
Hi,

are there any plans or a schedule for a new release? The last official release is from Dec 2021.

Support for Opsman 4.0 and the new Metric index feature would be great to have in an official release.

Thanks.
Tobias

**Comment by VihasMakwana** [comment]
It's happening soon! stay tuned.

**Comment by sbylica-splunk** [comment]
New release available:
https://github.com/cloudfoundry-community/splunk-firehose-nozzle/releases/tag/v1.3.0
