### ISSUE TITLE
Throttle CC calls if app is no longer in CC DB

### ISSUE THREAD

**Issue by muymoo** [cloudfoundry-community/splunk-firehose-nozzle#39]
We have about 120,000 events/s coming off the firehose. When we enable `ADD_APP_INFO`, we get into a state where there are logs coming off the firehose with app id's that no longer exist in the CC DB (this might be a separate probably on its own). This causes the nozzle to repeatedly call the CC API with the app guid that no longer exists. This significantly slows down the nozzle (by 90%). I've been trying some hacks with a syncmap that stores app id's which no longer exist and ignores those calls. The other option I've been thinking about is creating an empty app record in Boltdb. Ideas?

**Comment by muymoo** [comment]
A hack that I made "works" is to use a `syncmap` in the boltdb caching implementation:

```golang
import "golang.org/x/sync/syncmap"
...
	return &CachingBolt{
		GcfClient: gcfClientSet,
		Appdb:     db,
		missed:	   new(syncmap.Map), // Stores app guids that no longer exist in CC DB but are still coming off firehose
	}
...
	var ticker = time.Tick(1 * time.Hour)

	go func() {
		for range ticker {
			c.missed = new(syncmap.Map) // Clear the map once an hour
		}
	}()
...
func (c *CachingBolt) GetAppInfoCache(appGuid string) App {
	
	// App exists in cache
	if app := c.GetAppInfo(appGuid); app.Name != "" {
		return app
	}
	
	// App already missed, ignore
	if _, found := c.missed.Load(appGuid); found {
		return App{}
	}

	// First time seeing event from app
	apps:=c.GetAppByGuid(appGuid)
	if apps[0].Name == ""{
		
		// Remember not to look up this app again
		c.missed.Store(appGuid,0)
		return App{}
	}
	return apps[0]
}
```

**Comment by muymoo** [comment]
https://github.com/muymoo/splunk-firehose-nozzle/tree/feature/ignore-missing-apps

**Comment by chenziliang** [comment]
@muymoo Thanks for these changes. Could you please create a PR for this ?

**Comment by muymoo** [comment]
@chenziliang Would you like this to the firehose-to-syslog (https://github.com/cloudfoundry-community/firehose-to-syslog) repo instead of the vendor folder here?

**Comment by chenziliang** [comment]
Seems the root cause is in syslog which splunk nozzle leverage, i would suggest fixing problem there.

**Comment by muymoo** [comment]
This issue was moved to cloudfoundry-community/firehose-to-syslog#149
