### ISSUE TITLE
Populate fields with valid JSON when appropriate

### ISSUE THREAD

**Issue by drutstein** [cloudfoundry-community/splunk-firehose-nozzle#50]
Nozzle will currently push any data into fields as strings, but when valid JSON is encountered this should be stored in the field as JSON and not as a string with escaped characters allowed for nested JSON.  

This is already done in the firehose-to-syslog nozzle:

https://github.com/cloudfoundry-community/firehose-to-syslog/blob/develop/logging/logging_logrus.go#L73

**Comment by chenziliang** [comment]
@drutstein I think this is different. L73 of logging_logrus.go is initializing a the logrus fmt. 
May i ask what feature you are mentioning ? Are you talking about the enriching the events by specifying extra key/values ?

**Comment by psychickita** [comment]
@drutstein - understood. The issue is that entire payload is in JSON, so a JSON blob within anotherJSON blob - tricky at best. spath is the way to go.
the reason syslog nozzle can handle it well is because the main payload is just delimited text

**Comment by chenziliang** [comment]
This is a valid request. Thanks @drutstein

**Comment by chenziliang** [comment]
@drutstein Is this what you want ?

<img width="926" alt="screen shot 2017-07-20 at 7 35 28 am" src="https://user-images.githubusercontent.com/775911/28423292-84a9b8e4-6d1f-11e7-8aba-0677863a1de5.png">

**Comment by drutstein** [comment]
@chenziliang That's exactly it.  

The ultimate goal is using an app logging standard that we've developed internally which ends up in the msg field.  Based on this we can build a data model for the general CF fields (cf_app_id, event_type, etc) as well as the underlying internal logging format (also in JSON) then accelerate that data model.

**Comment by chenziliang** [comment]
Fix this in https://github.com/cloudfoundry-community/splunk-firehose-nozzle/pull/54
Already in dev branch, @drutstein could you please give it a try ?
