### ISSUE TITLE
Refactor main.go to make it testable and modular

### ISSUE THREAD

**Issue by chenziliang** [cloudfoundry-community/splunk-firehose-nozzle#52]
For now, there are lots of code branch in main.go, and lack of params verification, cleaning it up first to make it modular and add necessary unit test.

If other necessary checking need added, we can refine later.

**Comment by cholick** [comment]
Branch `index-routing` has a much, much cleaner implementation of the params parsing. It has other work you probably don't want to pull in now, but, I go so annoyed with all the ugly params in main that I did that config work at the same time. In retrospect, it should have been a separate PR.

**Comment by chenziliang** [comment]
@cholick This is great. I will pickup from index-routing branch since i will start working on that very sooon :).

**Comment by chenziliang** [comment]
@cholick Appreciate again for pointing me to index-routing branch

Took at index-routing branch. Basically i like the idea of using a Config object to hold all params. This this PR, same idea, use SplunkFirehoseNozzle to hold all of params, and going further attache some object create functions for SplunkFirehoseNozzle to make things easier to understand.

The key difference for the configuration between your enhancement and this PR are
1. In index-routing, every data member is public. Hence simplicity. In this PR, lots of gets/sets
2. In index-routing, we basically kill kingpin flag parser. Personally i am not an env variable fan but flags. The killing of kingpin make things look pretty since we don't need the kingpin.Parse all the stuffs
3. In index-routing, main.go looks still complex to me since the object creation and how everything glues together are still in the same function (long and quite some if/else branches, and as we add more code, it will be even longer). Developer need take some time to think how all this work together especially there are mock/dry run code branches.

I will take another shot to make things look pretty and simple by following your idea.

Let's see how everything works for the next PR :)

**Comment by chenziliang** [comment]
I like to use flags since it is easier for automation testing. Env variable is a little bit harder

**Comment by chenziliang** [comment]
Item 3, is one of the main reason of this PR :)

**Comment by chenziliang** [comment]
Fix this in https://github.com/cloudfoundry-community/splunk-firehose-nozzle/pull/53
