### ISSUE TITLE
Refactor to a more pluggable design

### ISSUE THREAD

**Issue by zacharya** [cloudfoundry-community/splunk-firehose-nozzle#6]
Hi @cholick,

First off, great framework here.  I had some test code a few months back that provided similar functionality, but this is much more mature and fleshed out.  I understand that this repo is Splunk specific, but I can't help but notice the design is very pluggable in terms of other sinks and drains.

I was hoping the Splunk-specific main.go could be broken out into it's own repo (or maybe leave that here and break out the framework into its own repo).  My specific use case is to send the data off via Kinesis, but I'm sure more use cases are out there for other platforms/clients.  It would be nice to just develop another sink and drain for use by the community rather than fork this entire thing and drift away.

Thanks.

**Comment by cholick** [comment]
Thanks Zach, the intent was to keep things well isolated and separated. The issues with breaking things out would just be the bandwidth needed to support and maintain two repositories and the cleaving between them. It's just out of scope of the work my team is doing.

There's nothing to say you couldn't still import a subset of packages and re-use things, it just wouldn't come with API stability guarantees.

**Comment by zacharya** [comment]
Completely understand. Thanks for the response.
