### ISSUE TITLE
[Enhancement] Limit number of apps queried

### ISSUE THREAD

**Issue by muymoo** [cloudfoundry-community/splunk-firehose-nozzle#64]
@chenziliang We need to be able to limit the number of pages/apps queried in the first app dump. Get all apps takes hours for us. Something like get the most recent 5,000 apps would be perfect.

**Comment by chenziliang** [comment]
@muymoo Thanks. According to cloudfoundry cloud controller REST API https://apidocs.cloudfoundry.org/268/apps/list_all_apps.html, seems we can't sort the app by timestamp and limited the returned results. @cholick could you please help confirm if we can do this ?

**Comment by chenziliang** [comment]
I took a look at the API again, maybe we can do it by using this API.

cf curl "/v2/apps?inline-relations-depth=2&order-direction=desc&results-per-page=5000" | jq '.resources | .[].metadata.updated_at'

**Comment by chenziliang** [comment]
Fixed in https://github.com/cloudfoundry-community/splunk-firehose-nozzle/pull/69
