### ISSUE TITLE
Need to refresh missing app bucket

### ISSUE THREAD

**Issue by muymoo** [cloudfoundry-community/splunk-firehose-nozzle#65]
When ignoring missing apps in the missing apps bucket, there needs to be a TTL for the nozzle to retry for those app's metadata again. 24hrs would be good for our case. @chenziliang

**Comment by chenziliang** [comment]
@muymoo I will add one param to support this requirement

**Comment by chenziliang** [comment]
@muymoo If you can elaborate some use cases why we need retry for the missing app again sometime late, it will be fantastic !

**Comment by chenziliang** [comment]
Fixed in https://github.com/cloudfoundry-community/splunk-firehose-nozzle/pull/68
